import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../components/auth/AuthProvider';
import { PasswordField } from '../../components/auth/PasswordField';
import authBackgroundMain from '../../assets/auth-background-main.png';

/**
 * Step 2 of the password-reset flow.
 *
 * The user lands here from the magic link generated by `resetPasswordForEmail`.
 * Supabase's auth client (with `detectSessionInUrl: true`) creates a transient
 * recovery session and emits the PASSWORD_RECOVERY event — captured by the
 * AuthProvider, which sets `recoveryMode = true`.
 *
 * Until the user submits a new password, the rest of the app should *not*
 * react to that session: ProtectedRoute / RoleGuard explicitly delegate to
 * this page when recoveryMode is on.
 */
export function ResetPasswordPage() {
  const navigate = useNavigate();
  const { session, loading, recoveryMode, updatePassword, isSupabaseConfigured, supabaseConfigError } =
    useAuth();

  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  // After a successful reset, give a small breather so the user reads the
  // confirmation, then send them to the login screen as freshly-signed-in.
  useEffect(() => {
    if (!success) return;
    const timer = setTimeout(() => navigate('/auth', { replace: true }), 1800);
    return () => clearTimeout(timer);
  }, [success, navigate]);

  async function handleSubmit(event) {
    event.preventDefault();
    setError(null);

    if (password.length < 8) {
      setError('Choisissez un mot de passe d’au moins 8 caractères.');
      return;
    }
    if (password !== confirm) {
      setError('Les deux mots de passe ne correspondent pas.');
      return;
    }

    setSubmitting(true);
    const result = await updatePassword(password);
    setSubmitting(false);

    if (result?.error) {
      setError(result.error.message ?? 'Mise à jour du mot de passe impossible.');
      return;
    }

    setSuccess(true);
  }

  // If the user navigates here directly without a session (no recovery link
  // consumed), guide them back to the request screen. We wait for the
  // AuthProvider bootstrap (`loading`) to finish so the message does not flash
  // during the brief hash-token exchange Supabase performs on landing.
  const noSession = isSupabaseConfigured && !loading && !session;

  return (
    <div
      className="foodiz-auth-page"
      style={{ '--foodiz-auth-bg-image': `url(${authBackgroundMain})` }}
    >
      <div className="foodiz-auth-bg" aria-hidden="true">
        <div className="foodiz-auth-bg__triangle" />
        <div className="foodiz-auth-bg__fold-shadow" />
        <div className="foodiz-auth-bg__grain" />
      </div>

      <div className="foodiz-auth-frame">
        <header className="foodiz-auth-header">
          <div className="foodiz-auth-wordmark-wrap">
            <div className="foodiz-auth-wordmark">Foodiz</div>
            <span className="foodiz-auth-wordmark-underline" aria-hidden="true" />
          </div>
        </header>

        <section className="foodiz-auth-card premium-card">
          <div className="foodiz-auth-card__top">
            <p className="eyebrow">Sécurité du compte</p>
            <h1>Choisir un nouveau mot de passe</h1>
            <p className="foodiz-auth-subtitle">
              Saisissez un nouveau mot de passe pour finaliser la réinitialisation de votre accès Foodiz.
            </p>
          </div>

          {!isSupabaseConfigured ? (
            <div className="auth-feedback auth-feedback--warning">
              <strong>Configuration locale incomplète.</strong>
              <span>{supabaseConfigError}</span>
            </div>
          ) : null}

          {noSession ? (
            <div className="auth-feedback auth-feedback--warning">
              <strong>Lien expiré ou invalide.</strong>
              <span>
                Demandez un nouveau lien de réinitialisation depuis{' '}
                <Link className="auth-link" to="/auth">
                  la page de connexion
                </Link>
                .
              </span>
            </div>
          ) : null}

          {success ? (
            <div className="auth-feedback auth-feedback--success">
              Mot de passe mis à jour. Redirection en cours…
            </div>
          ) : null}
          {error ? <div className="auth-feedback auth-feedback--error">{error}</div> : null}

          <form className="auth-form" onSubmit={handleSubmit}>
            <PasswordField
              label="Nouveau mot de passe"
              name="new-password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <PasswordField
              label="Confirmer le mot de passe"
              name="new-password-confirm"
              value={confirm}
              onChange={(e) => setConfirm(e.target.value)}
            />

            <button
              className="gold-button auth-submit"
              type="submit"
              disabled={submitting || success || noSession || !isSupabaseConfigured}
            >
              Mettre à jour mon mot de passe
            </button>

            {!recoveryMode && session ? (
              <p className="auth-inline-text muted">
                Vous êtes déjà connecté — vous pouvez tout de même mettre à jour votre mot de passe.
              </p>
            ) : null}

            <p className="auth-inline-text">
              <Link className="auth-link" to="/auth">
                Retour à la connexion
              </Link>
            </p>
          </form>
        </section>
      </div>
    </div>
  );
}
